// Dados iniciais de demonstração — usa os números reais do anexo do
// prompt (custos, pacotes, ruas, categorias) em vez de valores
// inventados. Serve para testar a interface antes da primeira operação
// real; qualquer registro pode ser apagado depois.
import type {
  Cliente,
  Configuracao,
  EtiquetaNFC,
  ItemEstoque,
  Lead,
  MovimentoEstoque,
  Pedido,
} from "../types";
import { gerarId } from "../lib/id";
import { somarDias, agoraISO } from "../lib/date";

const hoje = agoraISO();
const d = (offset: number) => somarDias(hoje, offset);

export const CONFIGURACAO_INICIAL: Configuracao = {
  custosUnitarios: {
    filamentoPorPlaca: 2.16,
    etiquetaNfc: 0, // não informado no anexo — ajuste em Configurações
    adesivoBase: 0.7,
    etiquetaQr: 0.2,
    energiaPorImpressao: 0.15,
    embalagem: 0, // não informado no anexo — ajuste em Configurações
    taxaPerdaPercentual: 8,
  },
  pacotes: [
    { id: "pacote-1", nome: "1 placa", numeroPlacas: 1, preco: 79, ativo: true },
    { id: "pacote-2", nome: "2 placas", numeroPlacas: 2, preco: 129, ativo: true },
    { id: "pacote-4", nome: "4 placas", numeroPlacas: 4, preco: 259, ativo: true },
    {
      id: "pacote-fundacao",
      nome: "Oferta de fundação",
      numeroPlacas: 1,
      preco: 99,
      ativo: true,
    },
  ],
  marca: {
    nome: "Plaquinhas NFC",
    socios: [
      { nome: "Sócio 1", telefone: "", email: "" },
      { nome: "Sócio 2", telefone: "", email: "" },
    ],
    prazoPadraoEntregaDias: 3,
    diasRetornoAcompanhamento: 30,
  },
};

const RUAS = [
  "Av. JBSQJ",
  "R. Nelson Cesar de Oliveira",
  "R. dos Alecrins",
  "R. dos Cajueiros",
  "R. Manoel Bôsco Ribeiro",
  "R. Ibitinga",
  "Av. Cassiano Ricardo",
] as const;

export const LEADS_INICIAIS: Lead[] = [
  {
    id: "lead-1",
    nomeEstabelecimento: "Barbearia Vintage",
    endereco: "Av. JBSQJ, 450",
    rua: RUAS[0],
    categoria: "barbearia",
    notaGoogle: 4.7,
    numeroAvaliacoes: 132,
    vizinhoReferencia: { nome: "Barbearia Nova Era", notaGoogle: 4.2, numeroAvaliacoes: 98 },
    situacao: "vendido",
    dataVisita: d(-12),
    atendidoPor: "Marco",
    eraDono: true,
    motivoDescarte: null,
    dataRetorno: null,
    observacoes: "Dono super receptivo, já indicou dois vizinhos.",
    historicoVisitas: [
      {
        id: gerarId(),
        data: d(-12),
        resultado: "vendido",
        atendidoPor: "Marco",
        eraDono: true,
        proximaAcao: "Entregar em 3 dias",
        dataRetorno: null,
        observacoes: "Fechou pacote de 2 placas na hora.",
      },
    ],
    clienteId: "cliente-barbearia-vintage",
    criadoEm: d(-14),
    atualizadoEm: d(-12),
  },
  {
    id: "lead-2",
    nomeEstabelecimento: "Pet Shop Amigo Fiel",
    endereco: "R. dos Alecrins, 88",
    rua: RUAS[2],
    categoria: "pet_shop",
    notaGoogle: 4.5,
    numeroAvaliacoes: 61,
    vizinhoReferencia: null,
    situacao: "interessado",
    dataVisita: d(-3),
    atendidoPor: "Marco",
    eraDono: false,
    motivoDescarte: null,
    dataRetorno: d(1),
    observacoes: "Gerente gostou, precisa confirmar com o dono na sexta.",
    historicoVisitas: [
      {
        id: gerarId(),
        data: d(-3),
        resultado: "interessado",
        atendidoPor: "Marco",
        eraDono: false,
        proximaAcao: "Voltar para fechar",
        dataRetorno: d(1),
        observacoes: "Gerente gostou, precisa confirmar com o dono.",
      },
    ],
    clienteId: null,
    criadoEm: d(-5),
    atualizadoEm: d(-3),
  },
  {
    id: "lead-3",
    nomeEstabelecimento: "Restaurante Sabor Caseiro",
    endereco: "R. dos Cajueiros, 210",
    rua: RUAS[3],
    categoria: "restaurante",
    notaGoogle: 3.1,
    numeroAvaliacoes: 84,
    vizinhoReferencia: { nome: "Restaurante Bom Prato", notaGoogle: 4.4, numeroAvaliacoes: 210 },
    situacao: "descartado",
    dataVisita: d(-8),
    atendidoPor: "Ana",
    eraDono: true,
    motivoDescarte: "Nota abaixo de 3,5 — risco de piorar a reputação.",
    dataRetorno: null,
    observacoes: "",
    historicoVisitas: [
      {
        id: gerarId(),
        data: d(-8),
        resultado: "descartado",
        atendidoPor: "Ana",
        eraDono: true,
        proximaAcao: null,
        dataRetorno: null,
        observacoes: "Nota muito baixa, não é um bom fit agora.",
      },
    ],
    clienteId: null,
    criadoEm: d(-9),
    atualizadoEm: d(-8),
  },
  {
    id: "lead-4",
    nomeEstabelecimento: "Ótica Visão Clara",
    endereco: "R. Manoel Bôsco Ribeiro, 55",
    rua: RUAS[4],
    categoria: "otica",
    notaGoogle: 4.8,
    numeroAvaliacoes: 640,
    vizinhoReferencia: null,
    situacao: "descartado",
    dataVisita: d(-6),
    atendidoPor: "Ana",
    eraDono: false,
    motivoDescarte: "Mais de 500 avaliações — a dor de poucas avaliações não existe aqui.",
    dataRetorno: null,
    observacoes: "",
    historicoVisitas: [],
    clienteId: null,
    criadoEm: d(-6),
    atualizadoEm: d(-6),
  },
  {
    id: "lead-5",
    nomeEstabelecimento: "Hamburgueria do Zé",
    endereco: "Av. Cassiano Ricardo, 1200",
    rua: RUAS[6],
    categoria: "hamburgueria",
    notaGoogle: 4.3,
    numeroAvaliacoes: 45,
    vizinhoReferencia: null,
    situacao: "a_visitar",
    dataVisita: null,
    atendidoPor: null,
    eraDono: null,
    motivoDescarte: null,
    dataRetorno: null,
    observacoes: "",
    historicoVisitas: [],
    clienteId: null,
    criadoEm: d(-1),
    atualizadoEm: d(-1),
  },
  {
    id: "lead-6",
    nomeEstabelecimento: "Padaria Pão Dourado",
    endereco: "R. Ibitinga, 300",
    rua: RUAS[5],
    categoria: "padaria",
    notaGoogle: 4.1,
    numeroAvaliacoes: 152,
    vizinhoReferencia: null,
    situacao: "visitado",
    dataVisita: d(-2),
    atendidoPor: "Marco",
    eraDono: false,
    motivoDescarte: null,
    dataRetorno: d(3),
    observacoes: "Funcionária ficou de repassar para o dono.",
    historicoVisitas: [
      {
        id: gerarId(),
        data: d(-2),
        resultado: "visitado",
        atendidoPor: "Marco",
        eraDono: false,
        proximaAcao: "Voltar e falar com o dono",
        dataRetorno: d(3),
        observacoes: "Funcionária ficou de repassar.",
      },
    ],
    clienteId: null,
    criadoEm: d(-2),
    atualizadoEm: d(-2),
  },
  {
    id: "lead-7",
    nomeEstabelecimento: "Estética Bella Pele",
    endereco: "R. Nelson Cesar de Oliveira, 77",
    rua: RUAS[1],
    categoria: "estetica",
    notaGoogle: 4.9,
    numeroAvaliacoes: 38,
    vizinhoReferencia: null,
    situacao: "a_visitar",
    dataVisita: null,
    atendidoPor: null,
    eraDono: null,
    motivoDescarte: null,
    dataRetorno: null,
    observacoes: "",
    historicoVisitas: [],
    clienteId: null,
    criadoEm: d(0),
    atualizadoEm: d(0),
  },
];

export const CLIENTES_INICIAIS: Cliente[] = [
  {
    id: "cliente-barbearia-vintage",
    nomeEstabelecimento: "Barbearia Vintage",
    nomeResponsavel: "Carlos Eduardo",
    telefoneResponsavel: "(12) 99123-4567",
    endereco: "Av. JBSQJ, 450 — São José dos Campos, SP",
    linkAvaliacaoGoogle: "https://g.page/r/barbearia-vintage-sjc/review",
    linkEncurtado: "https://avalia.link/barbearia-vintage",
    dataPrimeiroPedido: d(-12),
    indicadoPorClienteId: null,
    leadOrigemId: null,
    observacoes: "",
    criadoEm: d(-12),
    atualizadoEm: d(-12),
  },
  {
    id: "cliente-acai-da-esquina",
    nomeEstabelecimento: "Açaí da Esquina",
    nomeResponsavel: "Fernanda Lima",
    telefoneResponsavel: "(12) 98876-2233",
    endereco: "R. dos Cajueiros, 40 — São José dos Campos, SP",
    linkAvaliacaoGoogle: "https://g.page/r/acai-da-esquina-sjc/review",
    linkEncurtado: "https://avalia.link/acai-esquina",
    dataPrimeiroPedido: d(-30),
    indicadoPorClienteId: null,
    leadOrigemId: null,
    observacoes: "Cliente antigo, veio por indicação de outro comerciante da rua.",
    criadoEm: d(-30),
    atualizadoEm: d(-30),
  },
];

export const PEDIDOS_INICIAIS: Pedido[] = [
  {
    id: "pedido-1",
    codigo: "PED-0001",
    clienteId: "cliente-acai-da-esquina",
    pacoteId: "pacote-2",
    numeroPlacas: 2,
    valorCobrado: 129,
    custoUnitarioSnapshot: 3.47,
    dataVenda: d(-33),
    dataPrometidaEntrega: d(-30),
    etapa: "pago",
    historicoEtapas: [
      { etapa: "vendido", data: d(-33) },
      { etapa: "link_criado", data: d(-33) },
      { etapa: "arte_pronta", data: d(-32) },
      { etapa: "impresso", data: d(-31) },
      { etapa: "nfc_gravado", data: d(-31) },
      { etapa: "testado", data: d(-30) },
      { etapa: "entregue", data: d(-30) },
      { etapa: "pago", data: d(-30) },
    ],
    etiquetasIds: ["etiqueta-1", "etiqueta-2"],
    dataEntregaReal: d(-30),
    dataRetorno30Dias: d(0),
    retornoFeito: false,
    pago: true,
    dataPagamento: d(-30),
    leadOrigemId: null,
    observacoes: "",
    criadoEm: d(-33),
    atualizadoEm: d(-30),
  },
  {
    id: "pedido-2",
    codigo: "PED-0002",
    clienteId: "cliente-barbearia-vintage",
    pacoteId: "pacote-2",
    numeroPlacas: 2,
    valorCobrado: 129,
    custoUnitarioSnapshot: 3.47,
    dataVenda: d(-12),
    dataPrometidaEntrega: d(-9),
    etapa: "entregue",
    historicoEtapas: [
      { etapa: "vendido", data: d(-12) },
      { etapa: "link_criado", data: d(-12) },
      { etapa: "arte_pronta", data: d(-11) },
      { etapa: "impresso", data: d(-10) },
      { etapa: "nfc_gravado", data: d(-10) },
      { etapa: "testado", data: d(-9) },
      { etapa: "entregue", data: d(-9) },
    ],
    etiquetasIds: ["etiqueta-3", "etiqueta-4"],
    dataEntregaReal: d(-9),
    dataRetorno30Dias: d(21),
    retornoFeito: false,
    pago: false,
    dataPagamento: null,
    leadOrigemId: null,
    observacoes: "Combinado de pagar em dinheiro na entrega — ainda não passamos para receber.",
    criadoEm: d(-12),
    atualizadoEm: d(-9),
  },
  {
    id: "pedido-3",
    codigo: "PED-0003",
    clienteId: "cliente-acai-da-esquina",
    pacoteId: "pacote-1",
    numeroPlacas: 1,
    valorCobrado: 79,
    custoUnitarioSnapshot: 3.47,
    dataVenda: d(-4),
    dataPrometidaEntrega: d(-1),
    etapa: "nfc_gravado",
    historicoEtapas: [
      { etapa: "vendido", data: d(-4) },
      { etapa: "link_criado", data: d(-4) },
      { etapa: "arte_pronta", data: d(-3) },
      { etapa: "impresso", data: d(-2) },
      { etapa: "nfc_gravado", data: d(-1) },
    ],
    etiquetasIds: ["etiqueta-5"],
    dataEntregaReal: null,
    dataRetorno30Dias: null,
    retornoFeito: false,
    pago: false,
    dataPagamento: null,
    leadOrigemId: null,
    observacoes: "Atrasado — falta testar e entregar.",
    criadoEm: d(-4),
    atualizadoEm: d(-1),
  },
  {
    id: "pedido-4",
    codigo: "PED-0004",
    clienteId: "cliente-barbearia-vintage",
    pacoteId: "pacote-1",
    numeroPlacas: 1,
    valorCobrado: 79,
    custoUnitarioSnapshot: 3.47,
    dataVenda: d(0),
    dataPrometidaEntrega: d(3),
    etapa: "vendido",
    historicoEtapas: [{ etapa: "vendido", data: d(0) }],
    etiquetasIds: [],
    dataEntregaReal: null,
    dataRetorno30Dias: null,
    retornoFeito: false,
    pago: false,
    dataPagamento: null,
    leadOrigemId: null,
    observacoes: "Placa extra para o balcão de bebidas.",
    criadoEm: d(0),
    atualizadoEm: d(0),
  },
];

export const ETIQUETAS_INICIAIS: EtiquetaNFC[] = [
  {
    id: "etiqueta-1",
    codigoInterno: "NFC-0001",
    uid: "04:A2:1F:9B:3C:80",
    situacao: "entregue",
    pedidoId: "pedido-1",
    linkGravado: "https://avalia.link/acai-esquina",
    dataGravacao: d(-31),
    gravadoPor: "Marco",
    resultadoTeste: "aprovado",
    aparelhoTeste: "iPhone 13",
    dataTeste: d(-30),
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-35),
  },
  {
    id: "etiqueta-2",
    codigoInterno: "NFC-0002",
    uid: "04:A2:1F:9B:3C:81",
    situacao: "entregue",
    pedidoId: "pedido-1",
    linkGravado: "https://avalia.link/acai-esquina",
    dataGravacao: d(-31),
    gravadoPor: "Marco",
    resultadoTeste: "aprovado",
    aparelhoTeste: "iPhone 13",
    dataTeste: d(-30),
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-35),
  },
  {
    id: "etiqueta-3",
    codigoInterno: "NFC-0003",
    uid: "04:B7:2C:11:4D:02",
    situacao: "entregue",
    pedidoId: "pedido-2",
    linkGravado: "https://avalia.link/barbearia-vintage",
    dataGravacao: d(-10),
    gravadoPor: "Ana",
    resultadoTeste: "aprovado",
    aparelhoTeste: "Moto G54",
    dataTeste: d(-9),
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-15),
  },
  {
    id: "etiqueta-4",
    codigoInterno: "NFC-0004",
    uid: "04:B7:2C:11:4D:03",
    situacao: "entregue",
    pedidoId: "pedido-2",
    linkGravado: "https://avalia.link/barbearia-vintage",
    dataGravacao: d(-10),
    gravadoPor: "Ana",
    resultadoTeste: "aprovado",
    aparelhoTeste: "Moto G54",
    dataTeste: d(-9),
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-15),
  },
  {
    id: "etiqueta-5",
    codigoInterno: "NFC-0005",
    uid: "04:C4:9A:7E:11:5F",
    situacao: "gravada",
    pedidoId: "pedido-3",
    linkGravado: "https://avalia.link/acai-esquina-2",
    dataGravacao: d(-1),
    gravadoPor: "Marco",
    resultadoTeste: "nao_testado",
    aparelhoTeste: null,
    dataTeste: null,
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-4),
  },
  {
    id: "etiqueta-6",
    codigoInterno: "NFC-0006",
    uid: null,
    situacao: "em_estoque",
    pedidoId: null,
    linkGravado: null,
    dataGravacao: null,
    gravadoPor: null,
    resultadoTeste: "nao_testado",
    aparelhoTeste: null,
    dataTeste: null,
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-5),
  },
  {
    id: "etiqueta-7",
    codigoInterno: "NFC-0007",
    uid: null,
    situacao: "em_estoque",
    pedidoId: null,
    linkGravado: null,
    dataGravacao: null,
    gravadoPor: null,
    resultadoTeste: "nao_testado",
    aparelhoTeste: null,
    dataTeste: null,
    motivoDefeito: null,
    historicoRegravacoes: [],
    criadoEm: d(-5),
  },
  {
    id: "etiqueta-8",
    codigoInterno: "NFC-0008",
    uid: "04:11:22:33:44:55",
    situacao: "com_defeito",
    pedidoId: null,
    linkGravado: null,
    dataGravacao: d(-6),
    gravadoPor: "Ana",
    resultadoTeste: "reprovado",
    aparelhoTeste: "iPhone 13",
    dataTeste: d(-6),
    motivoDefeito: "Chip não regravava depois do terceiro teste — provável defeito de fábrica.",
    historicoRegravacoes: [],
    criadoEm: d(-6),
  },
];

export const ITENS_ESTOQUE_INICIAIS: ItemEstoque[] = [
  {
    id: "item-adesivo",
    nome: "Adesivo vinil base",
    tipo: "adesivo_vinil",
    unidade: "un",
    quantidadeAtual: 24,
    quantidadeMinima: 15,
    custoUnitario: 0.7,
    fornecedor: "Gráfica Center Vale",
    prazoReposicaoDias: 4,
    criadoEm: d(-60),
    atualizadoEm: d(-9),
  },
  {
    id: "item-papel-qr",
    nome: "Papel adesivo para o QR",
    tipo: "papel_qr",
    unidade: "un",
    quantidadeAtual: 40,
    quantidadeMinima: 20,
    custoUnitario: 0.2,
    fornecedor: "Gráfica Center Vale",
    prazoReposicaoDias: 4,
    criadoEm: d(-60),
    atualizadoEm: d(-9),
  },
  {
    id: "item-filamento",
    nome: "Filamento PETG",
    tipo: "filamento_petg",
    unidade: "g",
    quantidadeAtual: 1850,
    quantidadeMinima: 500,
    custoUnitario: 0.144, // ~R$2,16 a cada 15g usados por placa
    fornecedor: "3D Fila SJC",
    prazoReposicaoDias: 7,
    criadoEm: d(-60),
    atualizadoEm: d(-9),
  },
  {
    id: "item-embalagem",
    nome: "Embalagens",
    tipo: "embalagem",
    unidade: "un",
    quantidadeAtual: 8,
    quantidadeMinima: 10,
    custoUnitario: 0.9,
    fornecedor: "Embalagens SJC",
    prazoReposicaoDias: 5,
    criadoEm: d(-60),
    atualizadoEm: d(-9),
  },
];

export const MOVIMENTOS_ESTOQUE_INICIAIS: MovimentoEstoque[] = [
  {
    id: "mov-1",
    itemId: "item-adesivo",
    data: d(-60),
    tipo: "entrada",
    quantidade: 30,
    motivo: "Compra inicial",
    pedidoId: null,
  },
  {
    id: "mov-2",
    itemId: "item-embalagem",
    data: d(-60),
    tipo: "entrada",
    quantidade: 20,
    motivo: "Compra inicial",
    pedidoId: null,
  },
  {
    id: "mov-3",
    itemId: "item-adesivo",
    data: d(-9),
    tipo: "saida",
    quantidade: 2,
    motivo: "Consumo automático — PED-0002 entregue",
    pedidoId: "pedido-2",
  },
  {
    id: "mov-4",
    itemId: "item-embalagem",
    data: d(-9),
    tipo: "saida",
    quantidade: 2,
    motivo: "Consumo automático — PED-0002 entregue",
    pedidoId: "pedido-2",
  },
  {
    id: "mov-5",
    itemId: "item-embalagem",
    data: d(-2),
    tipo: "perda",
    quantidade: 1,
    motivo: "Embalagem amassada no transporte",
    pedidoId: null,
  },
];
